### ISSUE TITLE
Creating user/coach leads to internal server error on live version (works fine locally)

### ISSUE THREAD

**Issue by Per-Starke** [Per-Starke/NutritionRecSys#113]

**Comment by Per-Starke** [comment]
- [ ] writing a new rating also leads to that error. Seems like writing to the files in general does not work?

**Comment by gernotstarke** [comment]
writing files from several parallel sessions is deadly, and won't work reliably. 

(That's what databases have been invented for, to resolve such issues)

**Comment by gernotstarke** [comment]
one idea: have a ratings file per user, that avoids parallel writes (but increases file overhead).
