### ISSUE TITLE
Check: How long does file-writing take?

### ISSUE THREAD

**Issue by Per-Starke** [Per-Starke/NutritionRecSys#118]

**Comment by gernotstarke** [comment]
you need to differentiate between "append" and "create-new"...

appending to an already existing file might require that this file to be read from start. May take long for large files :-(

**Comment by Per-Starke** [comment]
Even for the largest file, the ratings file, only takes 0.00036s to append a rating at the end

**Comment by gernotstarke** [comment]
nope, timing error. See my comments in #119 - you're timing the OS buffer I/O, and not the physical write.
(usually to measure the latter you need hooks into the OS, which regular python won't allow.
