### ISSUE TITLE
Catch exceptions for concurrent writing?

### ISSUE THREAD

**Issue by Per-Starke** [Per-Starke/NutritionRecSys#119]

**Comment by gernotstarke** [comment]
concurrent write can lead to corrupted files and should be avoided at all cost!!

Therefore I suggest to AVOID concurrent writes by design (e.g. delegate writes to a database) or search for a framework that reliably handles serializing-parallel-requests.

**Comment by Per-Starke** [comment]
Actually, pythons seems to be quite smart at this and (if lines to be written are not exceeding a certain byte limit) deals with this by itself perfectly well, at least thats what I found out so far and also could approve while testing

**Comment by Per-Starke** [comment]
Really seems like python, if multiple writes to the same file at the same time are made, executes them consecutively, and no problems appear..

**Comment by gernotstarke** [comment]
one problem is that these things are difficult to test in python (and other languages), as:

- python asks the operating system to write certain bytes to file f
- the OS takes these bytes, looks for obvious errors and then returns "success"
- some time later (and from python you have NO way of knowing when) the actual physical write happens.
OSs handle that "under the hood". Even trying to re-read the bytes written will most likely come from an OS-internal buffer.

you're right - in many (if not most) cases that works quite reliable.
