### ISSUE TITLE
Sometimes internal server error when opening / starting webpage

### ISSUE THREAD

**Issue by Per-Starke** [Per-Starke/NutritionRecSys#125]
Not often and can't figure out when this happens

**Comment by Per-Starke** [comment]
If again, note down exact time and mail prof

**Comment by gernotstarke** [comment]
imho you need access to the server logfiles, to track the source of this error:

* operating system log
* web server log
* flask log?

**Comment by gernotstarke** [comment]
from my own experience, it's a great idea to briefly note what the reason for such problem was... so if it happens again in the future, you don't need to keep such info in your head.
