### ISSUE TITLE
CB Rec Algo suddenly gives error (online)

### ISSUE THREAD

**Issue by Per-Starke** [Per-Starke/NutritionRecSys#133]

**Comment by Per-Starke** [comment]
seems to work locally now, check online

**Comment by Per-Starke** [comment]
Does not work online, but can't reproduce locally - how to proceed??

**Comment by gernotstarke** [comment]
* Compare python and flask versions
* Add detailed logging before and after calling CBAlgo
* Get access to server log file
* write automated tests
