### ISSUE TITLE
cannot enter nutrition requirements

### ISSUE THREAD

**Issue by gernotstarke** [Per-Starke/NutritionRecSys#147]
when pressing the "enter requirements" button in the top menu navigation, I'm directed to a
https://temporary-server.de/random URL and given some receipt to rate,
but not entry form for nutrition requirements.

situation: another user is working in parallel to me, my user-id was 133

**Comment by Per-Starke** [comment]
You mean all the time? Or when you haven't rated the obligatory 10 recipes?
