### ISSUE TITLE
no receipts displayed, just titles

### ISSUE THREAD

**Issue by gernotstarke** [Per-Starke/NutritionRecSys#148]
instead of showing receipts, I am given only receipe names/titles.

This feels annoying, as I have to switch to another browser window all the time.
Will dramatically reduce acceptance!!

**Comment by Per-Starke** [comment]
The titles should be links that are clickable to get to the recipe, which I found the best way of doing it, or are there any recipe titles that are not clickable?? Then that's wrong and needs to be fixed!
