### ISSUE TITLE
Kernfragen Canvas

### ISSUE THREAD

**Issue by Per-Starke** [Per-Starke/NutritionRecSys#152]

**Comment by gernotstarke** [comment]
The arc42 Canvas provides a (very simple and short) option to describe the architecture of software systems. One (proven) approach starts with answering the following key questions (very briefly, each answer should not exceed the length of a tweet):

1. What is the (Business) goal of the system?
2. What are the 3 most important capabilities
3. What are the 3 most important quality attributes
4. What are the Key Stakeholders
5. What are the important neighboring systems
6. What are the most important internal components or building blocks, modules or functions?
7. What are the most important technologies
8. What are you proud of?
9. What were your worst decisions? 
10. What are known risks and issues?

**Comment by gernotstarke** [comment]
2. Most important capabilities

* anonymous users can rate (arbitrary) receipes
* known (named) users can rate receipes
* known users can rate receipes the system has recommended for their taste and previous ratings

**Comment by gernotstarke** [comment]
4. Most important stakeholders

* system owner (Per Starke)
* Prof. Thelen, will rate the bacholor thesis
* named users who get receipe recommendations
* coaches, who will (in the future) get support for their nutrition coaching

**Comment by gernotstarke** [comment]
5. Most important neighboring systems

* receipe service (via API)

**Comment by gernotstarke** [comment]
7. Most important technologies

* Python + flask
* use file system for data handling (instead of database)
* deploy on temporary server

**Comment by gernotstarke** [comment]
9. Worst decision

* not using docker + cloud infrastructure, but rely on manual deployment -> makes bugfix awquard and slow
* not having relevant automated tests
* not having a database like PostgreSQL

all these decisions were deliberately taken with simplicity in mind, as these topics were not core for the Bachelor thesis.

**Comment by gernotstarke** [comment]
10. Known issues

all listed in the [public repo on github](https://github.com/Per-Starke/NutritionRecSys/issues?q=is%3Aopen+is%3Aissue+label%3Abug)

**Comment by gernotstarke** [comment]
@Per-Starke the rest is up-to-you. My proposals should provide an adequate starting point.

I can support you in creating diagrams for 5. and 6.

**Comment by gernotstarke** [comment]
8. What decisions are you proud of?

* having developed the whole application in a public repository on Github
* requirements and issues as Github-issues, parially using a [Kanban-board](https://github.com/users/Per-Starke/projects/1)

**Comment by Per-Starke** [comment]
@gernotstarke can we have a look at this together maybe? Finding it really hard to put this into a thesis-worthy text...

**Comment by gernotstarke** [comment]
gerne. Sonntag nachmittag/früher Abend?

lG maddad
