### ISSUE TITLE
add resources and references for "software architecture documentation"

### ISSUE THREAD

**Issue by gernotstarke** [Per-Starke/NutritionRecSys#153]
* arc42 - the template and method for communicating software architectures: online https://arc42.org, extensive documentation plus examples on https://docs.arc42.org.
* arc42-by-example: Starke et. al: arc42 by Example, 3rd edition. E-book, https://leanpub.com/arc42byexample/
* UML - the Universal Modeling Language, starting point: https://developer.ibm.com/articles/an-introduction-to-uml/, especially the UML component diagram
* Archi, a tool for creating and maintaing architecture diagrams. Free version https://www.archimatetool.com/

**Comment by Per-Starke** [comment]
https://canvas.arc42.org
