### ISSUE TITLE
when to start using flask/sqlalchemy?

### ISSUE THREAD

**Issue by Per-Starke** [Per-Starke/NutritionRecSys#31]

**Comment by Per-Starke** [comment]
Sollte ich zuerst die Software bei mir lokal mit csv und ohne flask fertigstellen, und dann im letzen Schritt auf sqlalchemy + flask web anwendung umstellen, oder sollte ich das jetzt direkt zwischendrin schon beginnen, was ist da der sinnvollere Weg?

**Comment by gernotstarke** [comment]
just my 2cts: möglichst früh (also: sofort) in der geplanten Zielumgebung arbeiten - um mögliche Schwierigkeiten frühzeitig erkennen zu können.

**Comment by Per-Starke** [comment]
Flask: now
SQL: Try to stick with csv at first
