### ISSUE TITLE
User ID / anonymize?

### ISSUE THREAD

**Issue by Per-Starke** [Per-Starke/NutritionRecSys#33]

**Comment by Per-Starke** [comment]
Anonymize coach-user information & add passwords to login?

**Comment by gernotstarke** [comment]
just a notice: user data (real-names, user-ids and passwords) are sensitive information, and should be stored with great care.

Especially passwords should NEVER be stored directly, but only password-hashes can be stored (that makes it much harder if not impossible for attackers to steal credentials). If you need more details -> dm me

**Comment by Per-Starke** [comment]
@gernotstarke I'll get back to you once I'm on this topic! Thx :)

**Comment by Per-Starke** [comment]
- [ ] secure user pages if unauthorized coach tries to manually get to a users account

**Comment by Per-Starke** [comment]
- [ ] store information encrypted

**Comment by Per-Starke** [comment]
- [ ] for account creation, make sure not same id given multiple times

**Comment by Per-Starke** [comment]
- [ ] add / remove clients: check ids for validity
