### ISSUE TITLE
re-organize repo structure

### ISSUE THREAD

**Issue by Per-Starke** [Per-Starke/NutritionRecSys#41]

**Comment by gernotstarke** [comment]
why, and what will the target structure be?

**Comment by Per-Starke** [comment]
@gernotstarke because it has a currently very unorganized directory/file structure, I defo want to clean this up. Still thinking about the target structure though.

**Comment by gernotstarke** [comment]
I suggest to search for "python project structure good practices" - as many languages (I know from Java and Golang) have established conventions.

You could try out a new structure in a branch - and verify everything's working prior to merging the new structure back to main... (but you surely would have done that anyway)
