### ISSUE TITLE
Fix warning?

### ISSUE THREAD

**Issue by Per-Starke** [Per-Starke/NutritionRecSys#91]

**Comment by gernotstarke** [comment]
do you mean python or flask warnings?
In professional sw-engineering, it's considered good practice to reduce such warnings to zero (in other terms: warnings are considered errors apart from very rare cases).

That reduces the chances for runtime errors... which can be annoying for users

**Comment by Per-Starke** [comment]
@gernotstarke  ```RequestsDependencyWarning: urllib3 (2.0.0) or chardet (4.0.0)/charset_normalizer (3.1.0) doesn't match a supported version!
  warnings.warn( ```

Everything seems to work fine but of course I want to find out where this warning comes from and how to solve it, not just ignore it

**Comment by gernotstarke** [comment]
dependencies are a difficult topic everywhere - I assume that flask requires specific versions of the libraries mentioned here (urllib, chardet, charset_normalizer). But I don't know how flask handles/defines such dependency versions...

From Jekyll you know these Gemfiles with endless lists of library-version combos... (gemfile.lock)
