### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by Per-Starke** [Per-Starke/NutritionRecSys#98]
@gernotstarke What do you think I need/should do as documentation? Or ist no real documentation needed as I will probably use my thesis to describe how everything works?

**Comment by gernotstarke** [comment]
at least consider arc42 as an option for (technical) documentation - meaning how you organize your code, and how things work in your app.

Maybe some of that would be "overkill" for your thesis, but you could ask the arc42 creators if they want the tech-doc of your system as an example on the docs.arc42.org site... I'm sure they would help.

For the thesis alone, I assume that you don't need additional documentation.
